Repository kata-containers/runtime, pull requests merged in 2018-10, with the labels that each got.

#772 block: Advertise block support for q35
  virtcontainers/qemu_amd64.go
  virtcontainers/qemu_amd64_test.go
Labels: bug, stable-candidate

#506 network: Add support for macvlan and macvtap driver
  virtcontainers/network.go
  virtcontainers/network_test.go
  virtcontainers/qemu_arch_base.go
  virtcontainers/qemu_arch_base_test.go
Labels: enhancement, feature

#814 network: Sort endpoints by name
  virtcontainers/network.go
Labels: stable-candidate

#733 cli: add configuration option to use or not use host netns
  cli/config.go
  cli/config/configuration.toml.in
  cli/config_test.go
  cli/kata-env.go
  cli/kata-env_test.go
  cli/network.go
  cli/network_test.go
  virtcontainers/bridgedmacvlan_endpoint.go
  virtcontainers/bridgedmacvlan_endpoint_test.go
  virtcontainers/default_network.go
  virtcontainers/endpoint.go
  virtcontainers/macvtap_endpoint.go
  virtcontainers/network.go
  virtcontainers/network_test.go
  virtcontainers/physical_endpoint.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/qemu.go
  virtcontainers/qemu_arch_base_test.go
  virtcontainers/sandbox.go
  virtcontainers/tap_endpoint.go
  virtcontainers/veth_endpoint.go
  virtcontainers/veth_endpoint_test.go
  virtcontainers/vhostuser_endpoint.go
Labels: enhancement, feature, review
