Repository kata-containers/runtime, pull requests merged in 2018-09, with the labels that each got.

#682 network: always assign sandbox networkNS
  virtcontainers/default_network.go
  virtcontainers/sandbox.go
Labels: review

#699 versions: update kernel version 4.14.67
  versions.yaml
Labels: review

#639 config: Detect if VM memory smaller than image
  cli/config.go
  cli/config_test.go
  cli/kata-env_test.go
  cli/utils.go
  cli/utils_test.go
Labels: review

#703 # Kata Containers 1.3.0-rc0
  VERSION
Labels: review

#693 virtcontainers: remove sandboxConfig.VMConfig
  cli/config.go
  cli/config_test.go
  virtcontainers/api_test.go
  virtcontainers/documentation/api/1.0/api.md
  virtcontainers/example_pod_run_test.go
  virtcontainers/factory/factory.go
  virtcontainers/factory/factory_test.go
  virtcontainers/factory/template/template.go
  virtcontainers/hack/virtc/main.go
  virtcontainers/hypervisor.go
  virtcontainers/hypervisor_test.go
  virtcontainers/mock_hypervisor.go
  virtcontainers/mock_hypervisor_test.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/pkg/oci/utils_test.go
  virtcontainers/qemu.go
  virtcontainers/qemu_test.go
  virtcontainers/sandbox.go
  virtcontainers/vm.go
Labels: review

#710 cli: fix build
  cli/config.go
  cli/config_test.go
Labels: review

#676 qemu: Add rng virtio device
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/intel/govmm/qemu/qemu.go
  vendor/github.com/intel/govmm/qemu/qmp.go
  versions.yaml
  virtcontainers/device/config/config.go
  virtcontainers/qemu.go
  virtcontainers/qemu_arch_base.go
Labels: review

#712 kata_agent: disable cgroup namespace
  virtcontainers/kata_agent.go
Labels: review

#716 # Kata Containers 1.3.0-rc1
  VERSION
Labels: review

#722 kata_agent: disable cgroup namespace
  virtcontainers/kata_agent.go
Labels: review

#719 Set the queue size for Multiqueue virtio-net as the number of vCPUs on the guest.
  virtcontainers/hypervisor.go
  virtcontainers/mock_hypervisor.go
  virtcontainers/network.go
  virtcontainers/qemu.go
Labels: enhancement, review

#725 kata-env: Fix display of debug options
  cli/config.go
  cli/config_test.go
  cli/kata-env.go
  cli/kata-env_test.go
  virtcontainers/pkg/oci/utils.go
Labels: bug, review, stable-candidate

#588 cli: Error out if initrd/rootfs not define in config file
  cli/config.go
  cli/config_test.go
Labels: enhancement

#706 cli: add configuration option to enable/disable vhost_net
  Gopkg.lock
  Gopkg.toml
  cli/config.go
  cli/config/configuration.toml.in
  vendor/github.com/intel/govmm/qemu/qmp.go
  virtcontainers/hypervisor.go
  virtcontainers/network.go
  virtcontainers/qemu.go
  virtcontainers/qemu_arch_base.go
Labels: enhancement, review

#730 cli: kata-env: add runtime path to output
  cli/kata-env.go
  cli/kata-env_test.go
Labels: review

#723 kata_agent: disable cgroup namespace
  virtcontainers/kata_agent.go
Labels: review

#643 versions: Bump golang from 1.8.3 to 1.9.7
  versions.yaml
Labels: review

#684 factory: start proxy before assign vm to a sandbox
  virtcontainers/agent.go
  virtcontainers/cc_proxy.go
  virtcontainers/cc_proxy_test.go
  virtcontainers/factory/base/base.go
  virtcontainers/factory/cache/cache.go
  virtcontainers/factory/cache/cache_test.go
  virtcontainers/factory/direct/direct.go
  virtcontainers/factory/direct/direct_test.go
  virtcontainers/factory/factory.go
  virtcontainers/factory/factory_test.go
  virtcontainers/factory/template/template.go
  virtcontainers/factory/template/template_test.go
  virtcontainers/hyperstart_agent.go
  virtcontainers/hyperstart_agent_test.go
  virtcontainers/kata_agent.go
  virtcontainers/kata_agent_test.go
  virtcontainers/kata_builtin_proxy.go
  virtcontainers/kata_builtin_proxy_test.go
  virtcontainers/kata_proxy.go
  virtcontainers/kata_proxy_test.go
  virtcontainers/no_proxy.go
  virtcontainers/no_proxy_test.go
  virtcontainers/noop_agent.go
  virtcontainers/noop_agent_test.go
  virtcontainers/noop_proxy.go
  virtcontainers/noop_proxy_test.go
  virtcontainers/proxy.go
  virtcontainers/proxy_test.go
  virtcontainers/sandbox.go
  virtcontainers/vm.go
  virtcontainers/vm_test.go
Labels: enhancement, review

#737 kata-env: Fix display of debug options
  cli/config.go
  cli/config_test.go
  cli/kata-env.go
  cli/kata-env_test.go
  virtcontainers/pkg/oci/utils.go
Labels: stable-candidate

#624 virtcontainers: hotplug memory with kata-runtime update command.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kata-containers/agent/protocols/client/client.go
  vendor/github.com/kata-containers/agent/protocols/grpc/agent.pb.go
  vendor/google.golang.org/grpc/balancer.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/base/base.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/balancer_v1_wrapper.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codec.go
  vendor/google.golang.org/grpc/codes/code_string.go
  vendor/google.golang.org/grpc/codes/codes.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/go16.go
  vendor/google.golang.org/grpc/go17.go
  vendor/google.golang.org/grpc/grpclb.go
  vendor/google.golang.org/grpc/grpclb_picker.go
  vendor/google.golang.org/grpc/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/grpclb_util.go
  vendor/google.golang.org/grpc/interceptor.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/naming/go17.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/transport/control.go
  vendor/google.golang.org/grpc/transport/go16.go
  vendor/google.golang.org/grpc/transport/go17.go
  vendor/google.golang.org/grpc/transport/handler_server.go
  vendor/google.golang.org/grpc/transport/http2_client.go
  vendor/google.golang.org/grpc/transport/http2_server.go
  vendor/google.golang.org/grpc/transport/http_util.go
  vendor/google.golang.org/grpc/transport/transport.go
  virtcontainers/agent.go
  virtcontainers/api.go
  virtcontainers/api_test.go
  virtcontainers/container.go
  virtcontainers/hyperstart_agent.go
  virtcontainers/kata_agent.go
  virtcontainers/kata_agent_test.go
  virtcontainers/noop_agent.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/qemu.go
  virtcontainers/sandbox.go
  virtcontainers/vm.go
Labels: enhancement

#738 kata-env: Fix display of debug options
  cli/config.go
  cli/config_test.go
  cli/kata-env.go
  cli/kata-env_test.go
  virtcontainers/pkg/oci/utils.go
Labels: stable-candidate

#533 device: Add GPU device support
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/intel/govmm/qemu/qmp.go
  virtcontainers/device/config/config.go
  virtcontainers/device/drivers/vfio.go
  virtcontainers/device/drivers/vfio_test.go
  virtcontainers/qemu.go
Labels: feature
