Repository kata-containers/runtime, pull requests merged in 2019-06, with the labels that each got.

#1762 fc-toml: remove proxy section in config
  cli/config/configuration-fc.toml.in
Labels: backport

#1776 Disable default hugepages enabling for virtio-fs
  Makefile
Labels: backport

#1789 katautils: fix shim v2 fail to work with libnetwork
  pkg/katautils/hook.go
Labels: backport, bug

#1795 [cherry-pick 1.7]: katautils: fix shim v2 fail to work with libnetwork
  pkg/katautils/hook.go
Labels: team/test
