Repository kata-containers/runtime, pull requests merged in 2019-04, with the labels that each got.

#1427 qemu: fix qemu leak when failed to start container
  virtcontainers/api.go
  virtcontainers/sandbox.go
Labels: bug, stable-candidate

#1441 config: fix panic in type assertion
  pkg/katautils/config.go
Labels: stable-candidate

#1524 netmon: Fix bug in how routes are converted
  netmon/netmon.go
  netmon/netmon_test.go
Labels: bug, stable-candidate

#1532 stable 1.6 backport: netmon: Fix bug in how routes are converted
  netmon/netmon.go
  netmon/netmon_test.go
Labels: stable-candidate

#1533 Stable 1.5 backport: netmon: Fix bug in how routes are converted
  netmon/netmon.go
  netmon/netmon_test.go
Labels: stable-candidate

#1502 network: Make tcfilter model as default
  Makefile
  virtcontainers/network.go
Labels: stable-candidate

#1544 backport: 1.6.2 backport patches
  Makefile
  cli/kata-check_amd64_test.go
  containerd-shim-v2/service.go
  pkg/katautils/config.go
  versions.yaml
  virtcontainers/api_test.go
  virtcontainers/cgroups.go
  virtcontainers/container.go
  virtcontainers/network.go
Labels: stable-candidate

#1563 vc: remove BlockIndex from container state
  virtcontainers/container.go
  virtcontainers/sandbox_test.go
  virtcontainers/types/container.go
Labels: hackathon

#883 persist: baseline persist data format
  virtcontainers/api.go
  virtcontainers/container.go
  virtcontainers/container_test.go
  virtcontainers/device/api/interface.go
  virtcontainers/device/drivers/block.go
  virtcontainers/device/drivers/generic.go
  virtcontainers/device/drivers/vfio.go
  virtcontainers/device/drivers/vhost_user_blk.go
  virtcontainers/device/drivers/vhost_user_net.go
  virtcontainers/device/drivers/vhost_user_scsi.go
  virtcontainers/mount_test.go
  virtcontainers/persist.go
  virtcontainers/persist/api/config.go
  virtcontainers/persist/api/container.go
  virtcontainers/persist/api/device.go
  virtcontainers/persist/api/interface.go
  virtcontainers/persist/api/network.go
  virtcontainers/persist/api/sandbox.go
  virtcontainers/persist/api/version.go
  virtcontainers/persist/fs/fs.go
  virtcontainers/persist/fs/fs_test.go
  virtcontainers/persist/manager.go
  virtcontainers/persist/manager_test.go
  virtcontainers/persist/plugin/README.md
  virtcontainers/persist_test.go
  virtcontainers/sandbox.go
  virtcontainers/sandbox_test.go
  virtcontainers/virtcontainers_test.go
Labels: request-for-review

#1567 vc: change container rootfs to be a mount
  cli/create.go
  containerd-shim-v2/create.go
  pkg/katautils/create.go
  pkg/katautils/create_test.go
  virtcontainers/api.go
  virtcontainers/api_test.go
  virtcontainers/container.go
  virtcontainers/container_test.go
  virtcontainers/example_pod_run_test.go
  virtcontainers/kata_agent.go
  virtcontainers/kata_agent_test.go
  virtcontainers/mount.go
  virtcontainers/persist.go
  virtcontainers/persist/api/container.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/pkg/oci/utils_test.go
  virtcontainers/sandbox.go
  virtcontainers/sandbox_test.go
  virtcontainers/types/container.go
Labels: hackathon

#1541 Fix parallel make
  .gitignore
  Makefile
  cli/config-generated.go.in
Labels: bug, stable-candidate

#1442 Add agent trace support
  Gopkg.lock
  Gopkg.toml
  cli/config/configuration-fc.toml.in
  cli/config/configuration-qemu.toml.in
  cli/kata-env.go
  cli/kata-env_test.go
  pkg/katatestutils/utils.go
  pkg/katautils/config.go
  pkg/katautils/config_test.go
  vendor/github.com/clearcontainers/proxy/COPYING
  vendor/github.com/clearcontainers/proxy/api/doc.go
  vendor/github.com/clearcontainers/proxy/api/frame.go
  vendor/github.com/clearcontainers/proxy/api/payload.go
  vendor/github.com/clearcontainers/proxy/api/protocol.go
  vendor/github.com/clearcontainers/proxy/client/client.go
  vendor/github.com/kata-containers/agent/protocols/grpc/agent.pb.go
  vendor/github.com/mdlayher/vsock/conn_linux.go
  vendor/github.com/mdlayher/vsock/fd_linux.go
  vendor/github.com/mdlayher/vsock/listener_linux.go
  virtcontainers/agent.go
  virtcontainers/agent_test.go
  virtcontainers/kata_agent.go
  virtcontainers/kata_agent_test.go
  virtcontainers/kata_shim.go
  virtcontainers/noop_agent.go
  virtcontainers/noop_agent_test.go
  virtcontainers/pkg/types/errors.go
  virtcontainers/sandbox.go
  virtcontainers/vm_test.go
Labels: feature, release
