Repository kata-containers/runtime, pull requests merged in 2020-10, with the labels that each got.

#2996 clh: Support VFIO device unplug
  versions.yaml
  virtcontainers/clh.go
  virtcontainers/pkg/cloud-hypervisor/Makefile
  virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/VERSION
  virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  virtcontainers/pkg/cloud-hypervisor/client/client.go
  virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md
  virtcontainers/pkg/cloud-hypervisor/client/docs/SgxEpcConfig.md
  virtcontainers/pkg/cloud-hypervisor/client/docs/VmAddDevice.md
  virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go
  virtcontainers/pkg/cloud-hypervisor/client/model_sgx_epc_config.go
  virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go
  virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Labels: needs-forward-port, no-backport-needed

#2944 cpuset: don't set cpuset.mems in the guest
  virtcontainers/container.go
Labels: needs-backport, needs-forward-port, port-to-2.0

#2997 virtiofs: Disable DAX
  Makefile
Labels: needs-forward-port, no-backport-needed, port-to-2.0

#2990 version: upgrade qemu version to v5.1.0 for arm64
  versions.yaml
Labels: needs-forward-port

#2991 shimv2: handle ctx passed by containerd
  containerd-shim-v2/service.go
Labels: needs-backport, needs-forward-port

#2988 hypervisor: don't enforce a minimum memory setting
  pkg/katautils/config.go
  virtcontainers/hypervisor.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/pkg/oci/utils_test.go
Labels: needs-backport, needs-forward-port

#2922 runtime: Fix /var/lib/vc/sbs/${sid} dir residual
  virtcontainers/sandbox.go
  virtcontainers/sandbox_test.go
Labels: needs-forward-port, port-to-2.0

#2915 runtime: Don' call bindUnmountContainerRootfs if container's rootfs u…
  virtcontainers/container.go
  virtcontainers/kata_agent.go
  virtcontainers/mount.go
  virtcontainers/mount_test.go
Labels: needs-backport, needs-forward-port

#3003 Handle PCI paths more consistently
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kata-containers/agent/pkg/types/types.pb.go
  vendor/github.com/kata-containers/agent/protocols/grpc/agent.pb.go
  vendor/github.com/kata-containers/agent/protocols/grpc/health.pb.go
  vendor/github.com/kata-containers/agent/protocols/grpc/oci.pb.go
  virtcontainers/acrn.go
  virtcontainers/bridgedmacvlan_endpoint.go
  virtcontainers/clh.go
  virtcontainers/device/config/config.go
  virtcontainers/device/drivers/block.go
  virtcontainers/device/drivers/vhost_user_blk.go
  virtcontainers/endpoint.go
  virtcontainers/ipvlan_endpoint.go
  virtcontainers/kata_agent.go
  virtcontainers/kata_agent_test.go
  virtcontainers/macvtap_endpoint.go
  virtcontainers/network.go
  virtcontainers/persist/api/device.go
  virtcontainers/persist/api/network.go
  virtcontainers/physical_endpoint.go
  virtcontainers/pkg/types/pcipath.go
  virtcontainers/pkg/types/pcipath_test.go
  virtcontainers/pkg/types/types.go
  virtcontainers/qemu.go
  virtcontainers/sandbox.go
  virtcontainers/tap_endpoint.go
  virtcontainers/tuntap_endpoint.go
  virtcontainers/veth_endpoint.go
  virtcontainers/vhostuser_endpoint.go
Labels: needs-forward-port, no-backport-needed

#3035 gitignore: Ignore cli/containerd-shim-kata-v2/config-generated.go
  .gitignore
Labels: no-backport-needed, no-forward-port-needed

#3033 Fix some error reporting in listInterfaces() and listRoutes()
  virtcontainers/kata_agent.go
Labels: needs-backport, needs-forward-port
