Repository kata-containers/runtime, pull requests merged in 2020-11, with the labels that each got.

#3013 clh: Consolidate the code path for device unplug
  virtcontainers/clh.go
  virtcontainers/clh_test.go
Labels: needs-forward-port, no-backport-needed

#3042 readonly volume should be bind mounted readonly on the host
  virtcontainers/container.go
  virtcontainers/kata_agent.go
  virtcontainers/mount.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/sandbox_test.go
Labels: no-backport-needed, no-forward-port-needed

#3031 annotations: Improve asset annotation handling
  virtcontainers/hypervisor.go
  virtcontainers/hypervisor_test.go
  virtcontainers/pkg/annotations/annotations.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/pkg/oci/utils_test.go
  virtcontainers/sandbox.go
  virtcontainers/sandbox_test.go
  virtcontainers/types/asset.go
  virtcontainers/types/asset_test.go
  virtcontainers/virtcontainers_test.go
Labels: needs-backport, needs-forward-port

#3028 clh: let clh config build for arm64
  arch/arm64-options.mk
Labels: backport, forward-port

#2920 Call s.newStore.Destroy if globalSandboxList.addSandbox failed
  virtcontainers/sandbox.go
Labels: needs-forward-port, port-to-2.0

#2940 runtime: Call s.newStore.Destroy if globalSandboxList.addSandbox
  virtcontainers/sandbox.go
Labels: needs-forward-port

#3051 Backports: Read-only mount fixes for 1.11
  virtcontainers/container.go
  virtcontainers/kata_agent.go
  virtcontainers/mount.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/sandbox_test.go
Labels: no-backport-needed, no-forward-port-needed

#3048 mount fixes for stable-1.12
  virtcontainers/container.go
  virtcontainers/kata_agent.go
  virtcontainers/mount.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/sandbox_test.go
Labels: backport

#3005 Validate annotations that refer to binaries
  Makefile
  cli/config/configuration-acrn.toml.in
  cli/config/configuration-clh.toml.in
  cli/config/configuration-fc.toml.in
  cli/config/configuration-qemu-virtiofs.toml.in
  cli/config/configuration-qemu.toml.in
  pkg/katautils/config.go
  virtcontainers/hypervisor.go
  virtcontainers/persist.go
  virtcontainers/persist/api/config.go
  virtcontainers/pkg/annotations/annotations.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/pkg/oci/utils_test.go
Labels: needs-forward-port, no-backport-needed

#3060 [stable-1.12] Backport #3005
  Makefile
  cli/config/configuration-acrn.toml.in
  cli/config/configuration-clh.toml.in
  cli/config/configuration-fc.toml.in
  cli/config/configuration-qemu-virtiofs.toml.in
  cli/config/configuration-qemu.toml.in
  pkg/katautils/config.go
  virtcontainers/hypervisor.go
  virtcontainers/persist.go
  virtcontainers/persist/api/config.go
  virtcontainers/pkg/annotations/annotations.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/pkg/oci/utils_test.go
Labels: backport

#3070 release: Fix release candidate to major version upgrade check
  cli/release.go
  cli/release_test.go
Labels: backport

#3073 [backport] runtime: clh: disable virtiofs DAX when FS cache size is 0
  versions.yaml
  virtcontainers/clh.go
  virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md
  virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go
  virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Labels: no-backport-needed, no-forward-port-needed

#3065 runtime: sleep 1 second after GetOOMEvent failed
  containerd-shim-v2/wait.go
  virtcontainers/monitor.go
Labels: backport

#3082 virtcontainers: Don't set CTTY
  virtcontainers/shim.go
Labels: needs-backport, no-forward-port-needed

#3081 versions: Bump the newest-version of OpenShift
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3086 cli: make check subcommand more tolerant to failures
  cli/kata-check.go
  cli/kata-check_amd64_test.go
  cli/kata-check_test.go
  cli/release.go
Labels: forward-port
