Repository kata-containers/runtime, pull requests merged in 2020-09, with the labels that each got.

#2932 virtcontainers: Add unit test for utils/compare.go
  virtcontainers/utils/compare_test.go
Labels: needs-review

#2891 ci/openshift-ci: Enable openshift-ci
  .ci/openshift-ci/build.sh
  .ci/openshift-ci/images/Dockerfile
  .ci/openshift-ci/images/entrypoint.sh
Labels: blocked-by-metrics

#2976 kata-check: check for newer release
  Makefile
  cli/config-generated.go.in
  cli/kata-check.go
  cli/release.go
  cli/release_test.go
Labels: backport
