Repository kata-containers/runtime, pull requests merged in 2020-07, with the labels that each got.

#2793 Constrain the host sandbox cgroup for devices and cpusets by default when sandbox-cgroup-only selected
  Gopkg.lock
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/kubernetes/.bazelrc
  vendor/k8s.io/kubernetes/.bazelversion
  vendor/k8s.io/kubernetes/.kazelcfg.json
  vendor/k8s.io/kubernetes/BUILD.bazel
  vendor/k8s.io/kubernetes/CHANGELOG.md
  vendor/k8s.io/kubernetes/Godeps/LICENSES
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/Makefile
  vendor/k8s.io/kubernetes/Makefile.generated_files
  vendor/k8s.io/kubernetes/WORKSPACE
  vendor/k8s.io/kubernetes/cluster/gce/cos
  vendor/k8s.io/kubernetes/cluster/gce/custom
  vendor/k8s.io/kubernetes/cluster/gce/ubuntu
  vendor/k8s.io/kubernetes/logo/LICENSE
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/cpuset.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/api/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cluster-bootstrap/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/component-base/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cri-api/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/csi-translation-lib/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-controller-manager/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-proxy/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kubectl/docs/book/pages/container_debugging/copying_container_files.md
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kubelet/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/metrics/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-cli-plugin/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-controller/LICENSE
  vendor/k8s.io/kubernetes/third_party/forked/golang/LICENSE
  vendor/k8s.io/kubernetes/third_party/forked/golang/PATENTS
  vendor/k8s.io/kubernetes/third_party/forked/gonum/graph/LICENSE
  vendor/k8s.io/kubernetes/third_party/forked/ipvs/LICENSE
  vendor/k8s.io/kubernetes/third_party/forked/shell2junit/LICENSE
  vendor/k8s.io/kubernetes/third_party/go-srcimporter/LICENSE
  vendor/k8s.io/kubernetes/third_party/intemp/LICENSE
  vendor/k8s.io/kubernetes/third_party/multiarch/qemu-user-static/LICENSE
  virtcontainers/container.go
  virtcontainers/pkg/cgroups/manager.go
  virtcontainers/sandbox.go
  virtcontainers/sandbox_test.go
Labels: port-to-2.0

#2823 virtcontainers: vhost-user-blk/scsi are block device nodes
  virtcontainers/device/manager/utils.go
  virtcontainers/device/manager/utils_test.go
Labels: port-to-2.0

#2828 virtcontainers: Add to bridges unit test
  virtcontainers/types/bridges_test.go
Labels: needs-review, port-to-2.0

#2853 virtcontainers: Move unit tests for types/sandbox.go
  virtcontainers/sandbox_test.go
  virtcontainers/types/sandbox_test.go
Labels: needs-review

#2845 virtcontainers: Add function to capabilities test
  virtcontainers/types/capabilities_test.go
Labels: needs-review

#2836 virtcontainers: Expand unit test coverage for asset
  virtcontainers/types/asset_test.go
Labels: needs-review
