Repository kata-containers/runtime, pull requests merged in 2020-06, with the labels that each got.

#2725 virtcontainers: drop deferred func for GetAndSetSandboxBlockIndex()
  virtcontainers/acrn.go
  virtcontainers/sandbox.go
Labels: port-to-2.0

#2703 Add vIOMMU support to qemu q35
  Gopkg.lock
  Gopkg.toml
  cli/config/configuration-fc.toml.in
  cli/config/configuration-qemu-virtiofs.toml.in
  cli/config/configuration-qemu.toml.in
  pkg/katautils/config-settings.go.in
  pkg/katautils/config.go
  vendor/github.com/intel/govmm/qemu/qemu.go
  virtcontainers/hypervisor.go
  virtcontainers/pkg/annotations/annotations.go
  virtcontainers/pkg/oci/utils.go
  virtcontainers/pkg/oci/utils_test.go
  virtcontainers/qemu.go
  virtcontainers/qemu_amd64.go
  virtcontainers/qemu_arch_base.go
  virtcontainers/qemu_arch_base_test.go
  virtcontainers/qemu_arm64.go
  virtcontainers/qemu_ppc64le.go
  virtcontainers/qemu_s390x.go
Labels: port-to-2.0

#2767 qemu: Fix kernel_irqchip=split option for IOMMU enabled sandbox
  virtcontainers/qemu_amd64.go
  virtcontainers/qemu_amd64_test.go
Labels: port-to-2.0

#2777 shimv2: Use BUILDTAGS when building shimv2
  Makefile
Labels: backport

#2783 virtcontainers: Fix structured logging in cgroups package
  virtcontainers/api.go
  virtcontainers/pkg/cgroups/manager.go
Labels: backport, port-to-2.0

#2801 vendor: update govmm
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/intel/govmm/qemu/qmp.go
Labels: backport

#2775 virtcontainer/cgroup: create cgroup manager after creating the network
  virtcontainers/api.go
  virtcontainers/bridgedmacvlan_endpoint.go
  virtcontainers/device/config/config.go
  virtcontainers/device/drivers/generic.go
  virtcontainers/device/drivers/vfio.go
  virtcontainers/endpoint.go
  virtcontainers/ipvlan_endpoint.go
  virtcontainers/macvtap_endpoint.go
  virtcontainers/network.go
  virtcontainers/persist/api/device.go
  virtcontainers/physical_endpoint.go
  virtcontainers/qemu.go
  virtcontainers/sandbox.go
  virtcontainers/tap_endpoint.go
  virtcontainers/tuntap_endpoint.go
  virtcontainers/veth_endpoint.go
  virtcontainers/vhostuser_endpoint.go
  virtcontainers/vhostuser_endpoint_test.go
Labels: backport, port-to-2.0
