Repository kata-containers/runtime, pull requests merged in 2020-12, with the labels that each got.

#2980 shimv2: Add tracing
  containerd-shim-v2/service.go
Labels: needs-forward-port, needs-review, no-backport-needed

#3092 build: Remove default hypervisor message from build
  Makefile
Labels: no-backport-needed, no-forward-port-needed

#3108 github: Add github actions
  .github/workflows/main.yml
  .travis.yml
Labels: no-backport-needed, no-forward-port-needed

#3102 backport: versions: Update firecracker to 0.21.3
  versions.yaml
Labels: backport
