Repository kata-containers/runtime, pull requests merged in 2021-05, with the labels that each got.

#3162 versions: Upgrade to cloud-hypervisor v15.0
  versions.yaml
  virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Labels: no-backport-needed, no-forward-port-needed

#3037 qemu: fix stopSandbox() to work with newer docker
  virtcontainers/qemu.go
Labels: needs-forward-port, no-backport-needed

#2923 factory: Use lazy unmount
  cli/main.go
  virtcontainers/factory/template/template.go
  virtcontainers/factory/template/template_test.go
Labels: needs-backport, needs-forward-port

#3097 docs: update documentation to reflect qemu.log behavior
  cli/config/configuration-qemu-virtiofs.toml.in
  cli/config/configuration-qemu.toml.in
Labels: needs-forward-port, no-backport-needed
